### ISSUE TITLE
roscore crashes when installing on BeagleBone Black

### ISSUE THREAD

**Issue by drewm1980** [vmayoral/beagle-ros#5]
I tried installing via your script on a stock BeagleBone Black running the supplied Angstrom.  The whole installation went well, but when I try running roscore I eventually hit some xml parsing error:

started core service [/rosout]
load_parameters: unable to set parameters (last param was [/rosdistro=hydro]): <Fault 1: "<class 'xml.parsers.expat.ExpatError'>:not well-formed (invalid token): line 13, column 15">
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/roslaunch/**init**.py", line 275, in main
    p.start()
  File "/usr/lib/python2.7/site-packages/roslaunch/parent.py", line 268, in start
    self.runner.launch()
  File "/usr/lib/python2.7/site-packages/roslaunch/launch.py", line 644, in launch
    self._setup()
  File "/usr/lib/python2.7/site-packages/roslaunch/launch.py", line 631, in _setup
    self._load_parameters()
  File "/usr/lib/python2.7/site-packages/roslaunch/launch.py", line 328, in _load_parameters
    r  = param_server_multi()
  File "/usr/lib/python2.7/xmlrpclib.py", line 997, in __call__
    return MultiCallIterator(self.**server.system.multicall(marshalled_list))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])

**Comment by vmayoral** [comment]
@drewm1980 Thanks for notifying. It seems that the problem is somewhere at the [meta-ros](https://github.com/bmwcarit/meta-ros) recipes. Why don't you try cross-compiling the packages yourself and installing them by hand?

Currently the angstrom servers are not being cared as much as they used to so i'm not sure which version is being installed through the scripts. There's information about how to cross-compile packages and links to set up a basic Angstrom Distribution on the README.

Let me know if you need further assistance.

**Comment by drewm1980** [comment]
Hey, thanks for the reply!  I'm actually not that invested yet, though.  About 10 other things about the angstrom wasted my time unnecessarily, so I'll probably give the ubuntu image a shot next...  I don't have much interest in cross-compiling, it seems like an unnecessary hassle since these devices are powerful enough to compile their own code.  If there is a problem I want to just ssh into my robot from whatever machine I happen to be sitting at, fix it, and get the heck out.  For your work are you cross-compiling from and x86-64 / ubuntu to BBB / ubuntu?  Or are you working directly on the BBB?

**Comment by vmayoral** [comment]
@drewm1980 i'm personally working with a ubuntu FS. I can compile the ROS packages natively and it's much more comfortable/fast. I believe this would also fit your needs. You can grab the images from [here](http://www.armhf.com/index.php/boards/beaglebone-black/).

Regards

**Comment by drewm1980** [comment]
@victor, Ooops, accidentally hit send before I typed anything.  In general,
do you recommend flashing ubuntu onto your boards, or do you boot from a
uSD card?  I just want them to boot fast and automatically, and to have at
least the software that is not tied to hardware just work.  I have enough
cards for my BBB's to do ether.  This is a univesity project with 4-5 BBB's
doing heterogeneous tasks, and i want to make life easy for the guys that
come after me.  Using a uniform OS everywhere would go a long way, I think.

Cheers,
Andrew

**Comment by vmayoral** [comment]
@drewm1980 i share your thoughts. I personally use uSD cards. More space, more flexibility and easier to change from one robot to another (which is what i'm usually doing).

**Comment by storypku** [comment]
Have anybody figure out how to fix this bug? I came across it 5 years later...
